In [2]:
import numpy as np
import pandas as pd 

import warnings
warnings.filterwarnings('ignore')

In [3]:
from sklearn.datasets import load_boston

In [4]:
boston = load_boston()

In [5]:
X = boston.data

In [6]:
X.shape


(506, 13)

In [7]:
mu = X.mean(axis = 0)

X_ = (X - mu)
X_.shape

(506, 13)

In [8]:
S = np.dot(X_.T, X_)
S.shape

(13, 13)

In [9]:
lambdas, vectors = np.linalg.eig(S)

In [10]:
lambdas.shape

(13,)

In [11]:
vectors.shape

(13, 13)

In [12]:
V = vectors[:, :2]
V.shape

(13, 2)

In [13]:
X_.shape

(506, 13)

In [14]:
V.shape

(13, 2)

In [15]:
X_new = np.dot(X_, V)
X_new.shape

(506, 2)

In [16]:
X_new[:5]

array([[-119.81884272,   -5.56005586],
       [-168.89015548,   10.11620863],
       [-169.31170747,   14.0805323 ],
       [-190.23064226,   18.3024633 ],
       [-190.13345103,   16.09794743]])

In [17]:
from sklearn.decomposition import PCA

In [18]:
pca = PCA(n_components = 2)

In [19]:
pca.fit_transform(X)

array([[-119.81884272,   -5.56005586],
       [-168.89015548,   10.11620863],
       [-169.31170747,   14.0805323 ],
       ...,
       [-138.38716306,    0.9380922 ],
       [-137.50517338,    4.2518251 ],
       [-139.19033295,    1.00906423]])

In [20]:
pca.explained_variance_ratio_

array([0.80582318, 0.16305197])